events {}

http {
    include /etc/nginx/mime.types;

    pid /tmp/nginx.pid;

    client_body_temp_path /tmp/client_temp;

    server {
        listen 8080;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
