staticPublishPath: .
redirects:
  - source: /product
    destination: /product.html
    statusCode: 200
  - source: /about
    destination: /about.html
    statusCode: 200
  - source: /services
    destination: /services.html
    statusCode: 200
  - source: /solutions
    destination: /solutions.html
    statusCode: 200
  - source: /contact
    destination: /contact.html
    statusCode: 200
  - source: /company
    destination: /company.html
    statusCode: 200

